### ISSUE TITLE
TEST current functionality --- handle situation where you open login modal while in burger menu.

### ISSUE THREAD

**Issue by wayncheng** [novialim/VRooms#98]
- One option would be to exit the burger menu before opening login modal
- Could also apply conditional styling on login modal for this situation to keep user experience more focused/simple
- Could also redirect to a page for login rather than modal.

**Comment by aqupriyanka** [comment]
Currently implemented the same modal box feature to mobile, similar to web.
Please test it if it looks ok or we need to apply conditional styling or login page.

**Comment by aqupriyanka** [comment]
Integrated login modal box for mobile login
